# handler paths are relative to the root serverless.yml file that this is being merged into
determine-phone-number-type:
  handler: src/handlers/phone-number/determine-phone-number-type.handler
  events:
    - http:
        path: /determine-phone-number-type
        method: POST
        cors: true